---
- name: Install Jenkins CI/CD
  hosts: localhost
  become: true
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
        exclude: kernel*
    - name: Install packages needed for docker and its ecosystem
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - python3
          - python3-pip
        state: present
    - name: Set up a stable docker repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: Install docker packages
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - contairned.io
        state: present
    - name: Start Docker daemon
      service:
        name: docker
        state: started

