---
- name: Install Jenkins CI/CD
  hosts: localhost
  become: true
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
        exclude: kernel*
    - name: Install packages needed for docker and its ecosystem
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - python3
          - python3-pip
        state: present
    - name: Set up a stable docker repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: Install docker packages
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
    - name: start service
      service:
        name: docker
        state: started
    - name: Set current user to docker group
      command: usermod -aG docker {{ ansible_user }}
    - name: install gdown and docker-compose
      pip:
        virtualenv: /tmp/py3
        virtualenv_command: /usr/bin/python3 -m venv
        name:
          - gdown
          - docker-compose
    - name: download jenkins project file
      command: gdown https://drive.google.com/uc?id=1IsmZeQMKQ952TeKM7ggWlfx_0stsoJPn -O /opt/




